
all:
	$(MAKE) -C hexload/
	$(MAKE) -C helloworld/
	$(MAKE) -C TinyBasicPlus/
	$(MAKE) -C snake/

.PHONY clean:
	$(MAKE) -C init/ clean
	$(MAKE) -C pigfx/ clean
	$(MAKE) -C hexload/ clean
	$(MAKE) -C helloworld/ clean
	$(MAKE) -C TinyBasicPlus/ clean
	$(MAKE) -C snake/ clean
